var dir_b7e24418183484dddf339a907973acea =
[
    [ "compiler", "dir_644c7e5f760919e65c1bc3b37300f5dc.html", "dir_644c7e5f760919e65c1bc3b37300f5dc" ],
    [ "addressbook.h", "addressbook_8h.html", "addressbook_8h" ],
    [ "base.h", "base_8h.html", "base_8h" ],
    [ "csm.h", "csm_8h.html", "csm_8h" ],
    [ "date.h", "date_8h.html", "date_8h" ],
    [ "eeprom.h", "eeprom_8h.html", "eeprom_8h" ],
    [ "explorer.h", "explorer_8h.html", "explorer_8h" ],
    [ "file.h", "file_8h.html", "file_8h" ],
    [ "gbs.h", "gbs_8h.html", "gbs_8h" ],
    [ "gprs.h", "gprs_8h.html", "gprs_8h" ],
    [ "gui.h", "gui_8h.html", "gui_8h" ],
    [ "i2c.h", "i2c_8h.html", "i2c_8h" ],
    [ "idle.h", "idle_8h.html", "idle_8h" ],
    [ "image.h", "image_8h.html", "image_8h" ],
    [ "info.h", "info_8h.html", "info_8h" ],
    [ "java.h", "java_8h.html", "java_8h" ],
    [ "libc.h", "libc_8h.html", "libc_8h" ],
    [ "misc.h", "misc_8h.html", "misc_8h" ],
    [ "nucleus.h", "nucleus_8h.html", "nucleus_8h" ],
    [ "obs.h", "swilib_2obs_8h.html", "swilib_2obs_8h" ],
    [ "openssl.h", "openssl_8h.html", "openssl_8h" ],
    [ "patch.h", "patch_8h.html", "patch_8h" ],
    [ "player.h", "player_8h.html", "player_8h" ],
    [ "png.h", "swilib_2png_8h.html", "swilib_2png_8h" ],
    [ "settings.h", "settings_8h.html", "settings_8h" ],
    [ "socket.h", "swilib_2socket_8h.html", "swilib_2socket_8h" ],
    [ "sound.h", "sound_8h.html", "sound_8h" ],
    [ "system.h", "system_8h.html", "system_8h" ],
    [ "telephony.h", "telephony_8h.html", "telephony_8h" ],
    [ "ui.h", "ui_8h.html", "ui_8h" ],
    [ "utils.h", "utils_8h.html", "utils_8h" ],
    [ "wstring.h", "wstring_8h.html", "wstring_8h" ],
    [ "zlib.h", "swilib_2zlib_8h.html", "swilib_2zlib_8h" ]
];