var topics =
[
    [ "SWILIB", "group___s_w_i_l_i_b.html", "group___s_w_i_l_i_b" ],
    [ "Libc", "group__libc.html", "group__libc" ],
    [ "WSHDR", "group___w_s_h_d_r.html", "group___w_s_h_d_r" ],
    [ "DateTime", "group___date_time.html", "group___date_time" ],
    [ "GBS", "group___g_b_s.html", "group___g_b_s" ],
    [ "CSM", "group___c_s_m.html", "group___c_s_m" ],
    [ "GUI", "group___g_u_i.html", "group___g_u_i" ],
    [ "UI", "group___u_i.html", "group___u_i" ],
    [ "File", "group___file.html", "group___file" ],
    [ "Image", "group___image.html", "group___image" ],
    [ "PNG", "group___p_n_g.html", "group___p_n_g" ],
    [ "OBS", "group___o_b_s.html", "group___o_b_s" ],
    [ "Sound", "group___sound.html", "group___sound" ],
    [ "GPRS", "group___g_p_r_s.html", "group___g_p_r_s" ],
    [ "Socket", "group___socket.html", "group___socket" ],
    [ "OpenSSL", "group___open_s_s_l.html", "group___open_s_s_l" ],
    [ "Info", "group___info.html", "group___info" ],
    [ "System", "group___system.html", "group___system" ],
    [ "EEPROM", "group___e_e_p_r_o_m.html", "group___e_e_p_r_o_m" ],
    [ "Settings", "group___settings.html", "group___settings" ],
    [ "Telephony", "group___telephony.html", "group___telephony" ],
    [ "Addressbook", "group___addressbook.html", "group___addressbook" ],
    [ "Explorer", "group___explorer.html", "group___explorer" ],
    [ "Java", "group___java.html", "group___java" ],
    [ "I2C", "group___i2_c.html", "group___i2_c" ],
    [ "ZLIB", "group___z_l_i_b.html", "group___z_l_i_b" ],
    [ "Utils", "group___utils.html", "group___utils" ],
    [ "MISC", "group___m_i_s_c.html", "group___m_i_s_c" ],
    [ "PATCH", "group___p_a_t_c_h.html", "group___p_a_t_c_h" ],
    [ "IDLE", "group___i_d_l_e.html", "group___i_d_l_e" ],
    [ "NUCLEUS", "group___n_u_c_l_e_u_s.html", "group___n_u_c_l_e_u_s" ],
    [ "Player", "group___player.html", "group___player" ]
];