PROJECT := wstr
TARGET := NSG
BUILD_TYPE := exe
BUILD_DIR := bin

OPT := -Os
CPPFLAGS += -mthumb
LDLIBS += -lcrt -lcrt_helper -lgcc -lc

SOURCES += main.c

SDK_PATH := ../..
include $(SDK_PATH)/rules.mk
